"""tabelas iniciais

Revision ID: 72d53f3edad8
Revises: 
Create Date: 2026-04-26 10:25:13.235049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d53f3edad8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('inep_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'teacher', 'admin', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('lgpd_consent', sa.Boolean(), nullable=True),
    sa.Column('image_consent', sa.Boolean(), nullable=True),
    sa.Column('lichess_username', sa.String(length=100), nullable=True),
    sa.Column('level', sa.Enum('peao', 'cavalo', 'bispo', 'torre', 'dama', 'rei', name='studentlevel'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_id'), 'certificates', ['id'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_table('game_diaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('session_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reflection', sa.Text(), nullable=False),
    sa.Column('mood_rating', sa.Integer(), nullable=True),
    sa.Column('self_assessment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_diaries_id'), 'game_diaries', ['id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lichess_game_id', sa.String(length=20), nullable=True),
    sa.Column('pgn', sa.Text(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.Column('opening_name', sa.String(length=255), nullable=True),
    sa.Column('opening_eco', sa.String(length=5), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('player_color', sa.String(length=5), nullable=True),
    sa.Column('rating_before', sa.Integer(), nullable=True),
    sa.Column('rating_after', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lichess_game_id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_table('player_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('favorite_opening', sa.String(length=255), nullable=True),
    sa.Column('strongest_phase', sa.String(length=20), nullable=True),
    sa.Column('most_lost_piece', sa.String(length=10), nullable=True),
    sa.Column('recurring_error_pattern', sa.Text(), nullable=True),
    sa.Column('current_rating', sa.Integer(), nullable=True),
    sa.Column('peak_rating', sa.Integer(), nullable=True),
    sa.Column('total_games', sa.Integer(), nullable=True),
    sa.Column('total_puzzles', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_player_profiles_id'), 'player_profiles', ['id'], unique=False)
    op.create_table('puzzles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('lichess_puzzle_id', sa.String(length=20), nullable=True),
    sa.Column('fen', sa.String(length=100), nullable=False),
    sa.Column('solved', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('time_seconds', sa.Integer(), nullable=True),
    sa.Column('solved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puzzles_id'), 'puzzles', ['id'], unique=False)
    op.create_table('screen_time_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('session_start', sa.DateTime(), nullable=True),
    sa.Column('session_end', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('pause_notified', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screen_time_logs_id'), 'screen_time_logs', ['id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_table('game_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('blunders', sa.Integer(), nullable=True),
    sa.Column('mistakes', sa.Integer(), nullable=True),
    sa.Column('inaccuracies', sa.Integer(), nullable=True),
    sa.Column('missed_wins', sa.Integer(), nullable=True),
    sa.Column('opening_accuracy', sa.Float(), nullable=True),
    sa.Column('middlegame_accuracy', sa.Float(), nullable=True),
    sa.Column('endgame_accuracy', sa.Float(), nullable=True),
    sa.Column('moves_detail', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    op.create_index(op.f('ix_game_analyses_id'), 'game_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_analyses_id'), table_name='game_analyses')
    op.drop_table('game_analyses')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_screen_time_logs_id'), table_name='screen_time_logs')
    op.drop_table('screen_time_logs')
    op.drop_index(op.f('ix_puzzles_id'), table_name='puzzles')
    op.drop_table('puzzles')
    op.drop_index(op.f('ix_player_profiles_id'), table_name='player_profiles')
    op.drop_table('player_profiles')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_game_diaries_id'), table_name='game_diaries')
    op.drop_table('game_diaries')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_certificates_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_table('schools')
    # ### end Alembic commands ###
